const state={catalog:[],filtered:[],selected:null,category:"",source:""};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const humanBytes=n=>{if(!n)return "Unspecified";let v=n,u=0,a=["B","KiB","MiB","GiB"];while(v>=1024&&u<a.length-1){v/=1024;u++}return `${v.toFixed(u?1:0)} ${a[u]}`};
function toast(message,error=false){let el=document.createElement("div");el.className=`toast${error?" error":""}`;el.textContent=message;$("#toast-stack").append(el);setTimeout(()=>el.remove(),4200)}
async function api(path,options={}){let res=await fetch(path,{headers:{"Content-Type":"application/json"},...options});let data=await res.json();if(!res.ok)throw new Error(data.detail||"Request failed");return data}
function setView(name){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`${name}-view`));$('#view-title').textContent=name==='discover'?'Discover labs':'Running labs';if(name==='running')loadEpisodes()}
$$('.nav-item').forEach(x=>x.onclick=()=>setView(x.dataset.view));
async function loadCatalog(){try{let data=await api('/api/catalog');state.catalog=data.scenarios;fillSelect('#category',data.categories,'All categories');fillSelect('#source',data.sources,'All sources');filterCatalog()}catch(e){toast(e.message,true)}}
function fillSelect(id,items,label){let el=$(id);el.innerHTML=`<option value="">${label}</option>`+Object.entries(items).sort().map(([k,v])=>`<option value="${esc(k)}">${esc(k)} (${v})</option>`).join('')}
function filterCatalog(){let q=$('#search').value.trim().toLowerCase();state.category=$('#category').value;state.source=$('#source').value;state.filtered=state.catalog.filter(x=>(!state.category||x.category===state.category)&&(!state.source||x.source===state.source)&&(!q||`${x.title} ${x.id} ${x.tags.join(' ')}`.toLowerCase().includes(q)));renderList()}
function renderList(){let list=$('#challenge-list');$('#catalog-count').textContent=`${state.filtered.length.toLocaleString()} of ${state.catalog.length.toLocaleString()} runnable labs`;if(!state.filtered.length){list.innerHTML='<div class="empty-state"><h2>No matching labs</h2><p>Try changing the current filters.</p></div>';return}list.innerHTML=state.filtered.map(x=>`<button class="challenge ${x.id===state.selected?'active':''}" data-id="${esc(x.id)}"><h3>${esc(x.title)}</h3>${x.difficulty!=='unspecified'?`<span class="badge ${esc(x.difficulty.toLowerCase())}">${esc(x.difficulty)}</span>`:'<span></span>'}<p>${esc(x.category)} · ${esc(x.source)} · ${esc(x.runner)}</p></button>`).join('');$$('.challenge').forEach(x=>x.onclick=()=>selectScenario(x.dataset.id))}
async function selectScenario(id){state.selected=id;renderList();let panel=$('#detail-panel');panel.classList.remove('empty');panel.innerHTML='<div class="skeleton"></div><div class="skeleton"></div>';try{let x=await api(`/api/scenarios/${encodeURIComponent(id)}`);let kinds=(x.capabilities||[]).map(v=>typeof v==='object'?v.kind:v).filter(Boolean);panel.innerHTML=`<div class="detail-head"><div><p class="eyebrow">CHALLENGE BRIEFING</p><h2>${esc(x.title)}</h2><div class="detail-id">${esc(x.id)}</div></div><div class="detail-actions"><button class="primary-button" id="start-selected">Start lab</button></div></div><div class="chips"><span class="chip">${esc(x.category)}</span>${x.difficulty!=='unspecified'?`<span class="chip">${esc(x.difficulty)}</span>`:''}<span class="chip">${esc(x.source)}</span>${x.tags.slice(0,4).map(t=>`<span class="chip">#${esc(t)}</span>`).join('')}</div><p class="section-label">OBJECTIVE</p><p class="objective">${esc(x.objective)}</p><div class="detail-grid"><div class="metric"><span>DELIVERY</span><strong>${esc(x.runner)} · ${x.artifact_count} artifact${x.artifact_count===1?'':'s'}</strong></div><div class="metric"><span>CAPABILITIES</span><strong>${esc(kinds.join(', ')||'None declared')}</strong></div><div class="metric"><span>PLATFORM</span><strong>${esc((x.platform.os||[]).join(', ')||'Any')} · ${esc((x.platform.architectures||[]).join(', ')||'Any')}</strong></div><div class="metric"><span>RANGE BUDGET</span><strong>${humanBytes(x.constraints.memory_bytes)} · ${esc(x.constraints.wall_time_seconds||'?')} sec</strong></div></div><p class="section-label">COMPLETION CRITERIA</p><ul class="criteria">${(x.completion_criteria||[]).map(v=>`<li>${esc(v)}</li>`).join('')||'<li>No criteria supplied</li>'}</ul>`;$('#start-selected').onclick=()=>startLab(x.id)}catch(e){panel.innerHTML=`<div class="empty-state"><h2>Unable to load briefing</h2><p>${esc(e.message)}</p></div>`}}
async function startLab(id){try{let job=await api('/api/start',{method:'POST',body:JSON.stringify({scenario_id:id})});watchJob(job)}catch(e){toast(e.message,true)}}
async function randomLab(){try{let body=state.category?{category:state.category}:{};let job=await api('/api/start/random',{method:'POST',body:JSON.stringify(body)});watchJob(job)}catch(e){toast(e.message,true)}}
async function watchJob(job){let dock=$('#job-dock');dock.classList.remove('hidden');$('#job-title').textContent=job.operation;while(true){await new Promise(r=>setTimeout(r,700));try{job=await api(`/api/jobs/${job.id}`);$('#job-message').textContent=job.message;if(job.status==='complete'){dock.classList.add('hidden');toast('Lab operation completed');await loadEpisodes();setView('running');return}if(job.status==='failed'){dock.classList.add('hidden');toast(job.error||'Operation failed',true);return}}catch(e){dock.classList.add('hidden');toast(e.message,true);return}}}
async function loadEpisodes(){let grid=$('#episode-grid');grid.innerHTML='<div class="skeleton"></div>';try{let data=await api('/api/episodes');$('#active-count').textContent=data.episodes.length;if(!data.episodes.length){grid.innerHTML='<div class="empty-state"><div>◌</div><h2>No active labs</h2><p>Launch a selected challenge or let Colosseum choose one randomly.</p></div>';return}grid.innerHTML=data.episodes.map(x=>`<article class="episode-card"><div class="episode-top"><div><p class="eyebrow">${esc(x.scenario_id)}</p><h3>${esc(x.episode_id)}</h3></div><span class="live">● ${esc(x.status).toUpperCase()}</span></div><div class="prompt">${esc(x.prompt||'No target prompt available.')}</div><div class="episode-actions"><button class="ghost-button copy" data-prompt="${encodeURIComponent(x.prompt||'')}">Copy prompt</button><button class="ghost-button reset" data-id="${esc(x.episode_id)}">Reset</button><button class="danger-button stop" data-id="${esc(x.episode_id)}">Stop & delete</button></div></article>`).join('');$$('.copy').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(decodeURIComponent(b.dataset.prompt));toast('Prompt copied')});$$('.reset').forEach(b=>b.onclick=()=>confirmAction('Reset this episode?','Its state and files will be wiped, then the lab will start fresh.',()=>episodeAction(b.dataset.id,'reset')));$$('.stop').forEach(b=>b.onclick=()=>confirmAction('Stop and delete this lab?','Containers and the episode workspace will be permanently removed.',()=>episodeAction(b.dataset.id,'stop')))}catch(e){grid.innerHTML=`<div class="empty-state"><h2>Unable to load episodes</h2><p>${esc(e.message)}</p></div>`}}
function confirmAction(title,message,action){let d=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-message').textContent=message;d.onclose=()=>{if(d.returnValue==='confirm')action()};d.showModal()}
async function episodeAction(id,action){try{let job=await api(`/api/episodes/${encodeURIComponent(id)}/${action}`,{method:'POST'});watchJob(job)}catch(e){toast(e.message,true)}}
$('#search').oninput=filterCatalog;$('#category').onchange=filterCatalog;$('#source').onchange=filterCatalog;$('#random-button').onclick=randomLab;$('#refresh-episodes').onclick=loadEpisodes;loadCatalog();loadEpisodes();
